Client vote
zyazhb/dDDoS pull request #23
Opened 2021-07-31 05:58 UTC by mashiro01

1. 简化合约
2. 拆分出链端和监控端
3. 多客户端可相互输送信息

[](https://right-wolf-4d6.notion.site/744f69ff575d41d490f1f2b084a9b8ad)

2021-07-31 06:00 UTC, mashiro01 commented
https://right-wolf-4d6.notion.site/744f69ff575d41d490f1f2b084a9b8ad

2021-08-01 12:23 UTC, zyazhb commented on client/main.go
> +package main
为啥挪了主函数的位置？？？？

2021-08-01 12:23 UTC, zyazhb commented on config/config.yaml
> +  contract-address: '' # 填入获取的地址
为啥还会有server和client的说法？

2021-08-01 12:32 UTC, zyazhb commented on node/node.go
> +	"fmt"
改成log吧

2021-08-01 12:32 UTC, zyazhb commented on node/message.go
> +	voteTransHash	 = "0xe6d2d2c21284e671da4a773c628d519f81d37af2ae3950c34d207f567bb08f4e"
这里是固定值吗

2021-08-01 12:33 UTC, zyazhb commented on node/util.go
> +	ChainPort		int		`yaml:"chain-port"`
没格式化

2021-08-01 12:35 UTC, zyazhb commented on node/util.go
> +	Conf = conf
不是你这么写的吧 直接unmarshal的时候 把&Conf传进去不行么

2021-08-01 12:38 UTC, zyazhb requested changes
再沟通一下这个server和client的问题吧 好像有偏差了

2021-08-01 13:11 UTC, mashiro01 commented on node/message.go
> +	voteTransHash	 = "0xe6d2d2c21284e671da4a773c628d519f81d37af2ae3950c34d207f567bb08f4e"
嗯 这个的话必须要是固定值了 就是keccak256("eventname(param type ...)") 动态的话基本要半秒到一秒左右才能出结果 感觉不划算了

2021-08-01 13:11 UTC, mashiro01 commented on node/node.go
> +	"fmt"
![image](https://user-images.githubusercontent.com/30515297/127771622-06213714-6b89-4014-85a8-9f7f4863f282.png)
这个的话就是用过来拼接一次字符串的 ，其他的都用的log

2021-08-02 11:47 UTC, zyazhb commented on node/node.go
> +	"fmt"
用+

2021-08-02 11:58 UTC, zyazhb approved these changes

2021-08-02 11:59 UTC, merged